name: Benchmarks

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  benchmarks:
    if: False
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: Manan17
      REPO_NAME: testing
      OUTPUT_DIR: benchmarks
      OUTPUT_FILENAME: benchmark.csv
      GENERATED_CSV: data/all_benchmark_data.csv

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit hash
        id: get_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install modal
          pip install pandas

      - name: Remove previous benchmark data
        run: |
          rm -f data/all_benchmark_data.csv

      - name: Run benchmarks on GPU
        run: |
          python dev/benchmarks.py
        
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Copy generated benchmark to gh-pages
        run: |
          mkdir -p gh-pages/${OUTPUT_DIR}/${{ steps.get_hash.outputs.hash }}
          cp ${GENERATED_CSV} gh-pages/${OUTPUT_DIR}/${{ steps.get_hash.outputs.hash }}/${OUTPUT_FILENAME}

      - name: Update commits.txt
        run: |
          cd gh-pages
          echo "commits.txt file path: ${OUTPUT_DIR}/commits.txt"

          # Create file if it doesn't exist
          mkdir -p ${OUTPUT_DIR}
          touch ${OUTPUT_DIR}/commits.txt

          # Append only if not already present
          if ! grep -q "${{ steps.get_hash.outputs.hash }}" ${OUTPUT_DIR}/commits.txt; then
            echo "${{ steps.get_hash.outputs.hash }}" >> ${OUTPUT_DIR}/commits.txt
          fi

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Add benchmark for commit ${{ steps.get_hash.outputs.hash }}" || echo "No changes to commit"
          git push origin gh-pages

